omgggg

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,6 +9,30 @@ jobs:
     steps:
       - checkout
 
+
+      - run:
+    name: Debug directory structure
+    command: |
+      echo "Current directory:"
+      pwd
+      echo
+      echo "Files here:"
+      ls -al
+      echo
+      echo "Files in ~/project:"
+      ls -al ~/project
+      echo
+      echo "Files in ~/project/Lab7:"
+      ls -al ~/project/Lab7 || echo "Lab7 folder NOT FOUND"
+
+
+
+
+
+
+
+
+
       - run: ./gradlew androidDependencies
 
       - run: ./gradlew lint test
